### ISSUE TITLE
Grim Locations auto shutdown/ can't remove Grim Locations

### ISSUE THREAD

**Issue by PartytimeMentat** [recursivelftr/Grim-Locations#1]
Error log of 0.3 
[hs_err_pid612.log](https://github.com/recursivelftr/Grim-Locations/files/8142156/hs_err_pid612.log)

Error log of 1.0
[hs_err_pid924.log](https://github.com/recursivelftr/Grim-Locations/files/8142158/hs_err_pid924.log)
 
I haven't been able to start grim locations so I have manually deleted the folder, however after that I can't play with Grim Internals properly. after I manually modified the teleport list, the game showed black screen after Crate logo, after I reinstalled Grim internals it worked but if I changed the Teleport list it would happen again. a grimlocation_chars.txt is always generated even if I deleted the grim location. if I deleted that file, Grim Internals encountered the same black screen error. any ideas?

**Comment by recursivelftr** [comment]
grimlocation_chars.txt wouldn't be effecting this. Thats just a file generated by Grim Internals for use in Grim Locations. If you don't have Grim Locations running the file is never used. Please take a look at the article below, it may solve both your issues, the Grim Dawn black screen and Grim Locations not starting.

Also, once you have run version 1.0 of Grim Locations version 0.3 will no longer start properly. This is due to database changes made by 1.0.

https://ugetfix.com/ask/how-to-fix-exception-access-violation-error-on-windows-10/
