### ISSUE TITLE
GL crashing

### ISSUE THREAD

**Issue by grenhunterz** [recursivelftr/Grim-Locations#2]
Hi Recursive, I have issues with GL crashing very often. I've loaded GI x64 and selected my character, then opened GL and when I try to select locations on my active character, GL crashes. I've only had 1-2 times when I've been able to use GL successfully with GI and gog galaxy running as well.

**Comment by recursivelftr** [comment]
The issue seems to be cause by nvwgf2umx.dll not allowing memory to be accessed. nvwgf2umx.dll is an Nvidia driver dll so try performing a clean install of your drivers. If that doesn't work google nvwgf2umx.dll and EXCEPTION_ACCESS_VIOLATION.

A lot of people have run into the same problem with that dll file effecting various applications.

**Comment by grenhunterz** [comment]
TY. I've just performed a clean install of my drivers and GL is working great. TY for your assist.
